### ISSUE TITLE
Cannot claim and stake

### ISSUE THREAD

**Issue by D1ke2390** [jet-lab/jet-engine#92]
Hi, I'm trying to claim and stake the retroactive airdrop but once i hit the claim button it just stays there and no transaction shows up in my wallet to confirm it. I tried it on 3 different browsers and 2 different wallets. Thanks

**Comment by GHesericsu** [comment]
Yup we have identified the bug. This will be fixed shortly.

**Comment by GHesericsu** [comment]
Wrong repo for airdrop claim issue. Please refer to https://github.com/jet-lab/jet-governance
